name: ESLint

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        # creates report only if there are errors
        run: npx eslint tests/*/**.js -o ./test-results/eslint-report.html

      - name: Upload ESLint report
        uses: actions/upload-artifact@v2
        with:
          name: eslint-report
          path: ./test-results/eslint-report.html
