name: QA Metrics Benchmark

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'

      - name: Install Dependencies
        run:  |       
          npm ci
          npx playwright install chromium

      - name: Start the application
        run: npm run start & npx wait-on http://localhost:3000

      - name: Run Tests
        run: npx playwright test tests/qa

      - name: Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
