name: Quality Assurance Tests

on:
  workflow_dispatch:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        npm install glob --save-dev

    - name: Run CodeQL analysis
      run: npx @github/codeql-action/codeql-analysis -o sarif-results.sarif --sarif-file=codeql.sarif
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run ESLint
      run: npm run lint

    - name: Run website metrics tests
      uses: Microsoft/playwright-github-action@v1.7.0
      with:
        playwright-version: 1.14.0
        browser: chromium
        scriptPath: ./tests/website-metrics.test.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
