name: SEO Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run:
          npx playwright install
          npx playwright test tests/seo

      - name: Generate Report
        uses: cypress-io/github-action@v2.10.1
        with:
          files: |
            **/test-results.xml
          working-directory: test
          reporter: junit

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-results
