name: W3C HTML Validation

on:
  push:
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y w3c-markup-validator
      
      - name: Validate HTML files
        run: |
          find src/ -name "*.html" -type f -print0 | xargs -0 -n 1 -P 4 /usr/bin/validate -d /usr/share/xml/xhtml/schema/dtd/4.01/xhtml1-transitional.dtd
